import { ThemeConfig } from "../types";

export const THEMES: ThemeConfig[] = [
  {
    id: "immersive",
    name: "Immersive UI Pro",
    emoji: "🔮",
    fontSans: "font-sans",
    fontDisplay: "font-sans font-bold tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400 uppercase",
    fontMono: "font-mono text-[10px] uppercase tracking-[0.2em] text-purple-400",
    bgClass: "bg-[#0a0510] text-white min-h-screen transition-all duration-700 ease-in-out relative overflow-hidden before:absolute before:-inset-10 before:bg-[radial-gradient(circle_at_center,rgba(168,85,247,0.12)_0%,transparent_60%)] before:pointer-events-none before:z-0",
    cardClass: "bg-white/[0.03] backdrop-blur-xl border border-white/10 rounded-[32px] p-6 relative overflow-hidden shadow-[0_4px_30px_rgba(0,0,0,0.4)]",
    textPrimary: "text-white font-medium",
    textSecondary: "text-white/60 font-sans text-xs",
    accentColor: "purple-500",
    accentHex: "#a855f7",
    visualizerStyle: "immersive-glow",
    equalizerColor: "bg-purple-500 hover:bg-purple-400",
    vinylAnimate: true,
    additionalStyles: "immersive-glow"
  },
  {
    id: "synthwave",
    name: "Midnight Synthwave",
    emoji: "🌌",
    fontSans: "font-sans",
    fontDisplay: "font-sans tracking-widest uppercase font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-500 via-purple-500 to-cyan-400",
    fontMono: "font-mono text-[10px] uppercase text-cyan-400",
    bgClass: "bg-radial from-slate-900 via-indigo-950 to-slate-950 text-white min-h-screen transition-all duration-700 ease-in-out relative overflow-hidden before:absolute before:inset-0 before:bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] before:bg-[size:100%_4px,3px_100%] before:pointer-events-none before:z-40",
    cardClass: "bg-slate-900/80 border-2 border-pink-500/50 shadow-[0_0_20px_rgba(236,72,153,0.3)] rounded-xl backdrop-blur-md p-6 relative overflow-hidden after:absolute after:bottom-0 after:left-0 after:right-0 after:h-[2px] after:bg-gradient-to-r after:from-pink-500 after:via-purple-500 after:to-cyan-400",
    textPrimary: "text-white font-medium",
    textSecondary: "text-slate-400 font-mono text-xs",
    accentColor: "pink-500",
    accentHex: "#ec4899",
    visualizerStyle: "neon-bars",
    equalizerColor: "bg-pink-500 hover:bg-pink-400",
    vinylAnimate: true,
    additionalStyles: "synthwave-grid"
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk Overdrive",
    emoji: "🤖",
    fontSans: "font-mono",
    fontDisplay: "font-mono uppercase font-black text-yellow-300 tracking-tighter skew-x-3",
    fontMono: "font-mono text-xs text-lime-400",
    bgClass: "bg-zinc-950 text-yellow-300 min-h-screen transition-all duration-700 ease-in-out relative before:absolute before:inset-0 before:bg-[radial-gradient(#1a1a10_1px,transparent_1px)] before:bg-[size:16px_16px] before:opacity-30",
    cardClass: "bg-zinc-900 border-4 border-yellow-300 shadow-[4px_4px_0px_#000,8px_8px_0px_#84cc16] rounded-none p-6 border-r-lime-400 border-b-lime-400 relative clip-corner",
    textPrimary: "text-yellow-100 uppercase tracking-wider font-semibold",
    textSecondary: "text-zinc-400 font-mono",
    accentColor: "yellow-300",
    accentHex: "#fde047",
    visualizerStyle: "digital-matrix",
    equalizerColor: "bg-yellow-300 hover:bg-yellow-200",
    vinylAnimate: true,
    additionalStyles: "cyberpunk-borders"
  },
  {
    id: "forest",
    name: "Forest Moss",
    emoji: "🌲",
    fontSans: "font-sans",
    fontDisplay: "font-sans font-medium tracking-tight text-emerald-800",
    fontMono: "font-sans text-xs text-emerald-600 italic",
    bgClass: "bg-stone-100 text-stone-800 min-h-screen transition-all duration-700 ease-in-out relative overflow-hidden before:absolute before:-top-40 before:-left-40 before:w-96 before:h-96 before:bg-emerald-200/30 before:rounded-full before:filter before:blur-3xl before:pointer-events-none",
    cardClass: "bg-white/80 border border-emerald-100 shadow-[0_10px_30px_rgba(6,78,59,0.04)] rounded-3xl p-6 backdrop-blur-md relative",
    textPrimary: "text-emerald-900 font-semibold",
    textSecondary: "text-emerald-700/60 font-sans text-xs",
    accentColor: "emerald-600",
    accentHex: "#059669",
    visualizerStyle: "organic-leaves",
    equalizerColor: "bg-emerald-600 hover:bg-emerald-500",
    vinylAnimate: true
  },
  {
    id: "royal",
    name: "Crimson Velvet",
    emoji: "👑",
    fontSans: "font-serif",
    fontDisplay: "font-serif italic font-bold text-amber-100 tracking-wide",
    fontMono: "font-sans text-xs text-amber-400/80 uppercase tracking-widest",
    bgClass: "bg-gradient-to-br from-red-950 via-neutral-950 to-amber-950 text-amber-100 min-h-screen transition-all duration-700 ease-in-out relative",
    cardClass: "bg-red-950/40 border-2 border-amber-600/40 shadow-[0_15px_50px_rgba(217,119,6,0.15)] rounded-2xl p-6 backdrop-blur-lg relative before:absolute before:inset-[4px] before:border before:border-amber-500/10 before:rounded-xl before:pointer-events-none",
    textPrimary: "text-amber-100 font-serif",
    textSecondary: "text-amber-300/60 font-mono text-xs",
    accentColor: "amber-500",
    accentHex: "#f59e0b",
    visualizerStyle: "golden-rings",
    equalizerColor: "bg-amber-500 hover:bg-amber-400",
    vinylAnimate: true
  },
  {
    id: "glass",
    name: "Glass Minimalist",
    emoji: "❄️",
    fontSans: "font-sans",
    fontDisplay: "font-sans font-normal tracking-tighter text-slate-900",
    fontMono: "font-mono text-xs text-slate-400",
    bgClass: "bg-gradient-to-tr from-slate-200 via-neutral-100 to-indigo-100 text-slate-800 min-h-screen transition-all duration-700 ease-in-out",
    cardClass: "bg-white/40 border border-white/60 shadow-[0_8px_32px_rgba(31,38,135,0.06)] rounded-3xl p-6 backdrop-blur-xl relative",
    textPrimary: "text-slate-800 font-semibold",
    textSecondary: "text-slate-500 font-sans text-xs",
    accentColor: "indigo-600",
    accentHex: "#4f46e5",
    visualizerStyle: "glass-wave",
    equalizerColor: "bg-indigo-600 hover:bg-indigo-500",
    vinylAnimate: true
  },
  {
    id: "vinyl",
    name: "Retro Vinyl Cabinet",
    emoji: "📻",
    fontSans: "font-sans",
    fontDisplay: "font-mono uppercase font-extrabold text-amber-950 tracking-wide",
    fontMono: "font-mono text-xs text-amber-800",
    bgClass: "bg-orange-50 text-amber-950 min-h-screen transition-all duration-700 ease-in-out relative before:absolute before:inset-0 before:bg-[radial-gradient(#d97706_1px,transparent_1px)] before:bg-[size:24px_24px] before:opacity-10",
    cardClass: "bg-amber-100 border-8 border-amber-950 shadow-[10px_10px_0px_#78350f] rounded-2xl p-6 relative before:absolute before:top-2 before:left-2 before:right-2 before:bottom-2 before:border-2 before:border-dashed before:border-amber-900/20 before:rounded-lg before:pointer-events-none",
    textPrimary: "text-amber-950 font-bold uppercase tracking-wider",
    textSecondary: "text-amber-800/70 font-sans text-xs italic",
    accentColor: "amber-800",
    accentHex: "#92400e",
    visualizerStyle: "analog-vu",
    equalizerColor: "bg-amber-900 hover:bg-amber-800",
    vinylAnimate: true
  }
];
